# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: List all tasks
    cmds:
      - task --list-all

  check-required-bins-are-executables:
    desc: Check if required binaries are executable
    cmds:
      - bin/age --version
      - bin/age-keygen --version
      - bin/helm version
      - bin/helmfile version
      - bin/kind version
      - bin/sops --version
      - bin/task --version
      - docker version
