githubConfigSecret:
    github_token: ENC[AES256_GCM,data:t/gE/Go5G9y9DNkB3EVAQLFHCjOP1iArL5fmbizf6t3k5YIHnBRJvw==,iv:E3ss03/SQ0OEBx8GdZDXg2R7YMqHTT/iX3FpxkFt3gY=,tag:evLDqgqbGuYaa+p87gf1rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wkgxl8zfy9sdy4pz4lqz930mex28uwmxckejwh7a7h7q9xu954qqgl86kg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQ0R1dnoyR0cvaG5mYzF5
            QTZFTFprV1ZlQVdnUG9pM0ZROS9qcVNzOWhvCmVSaFQ5T2VPenVoNEZQbEhYSDY4
            WGZCendTaW5CR2RRa2RBS1I2NVhyOUEKLS0tIFZWK3lIY3ZISE9SdW52cGdoWVJT
            cFpsVU1EVGdXUU54YjZtWmt6K0dqUUUK7GVNehAXeeQ02jDtFceDvq61Pq8NiDCR
            D4GBmCR5EQcKra/LKp86NLxPPSbUwEUnAeDeNd7K33M8ekvhybIsog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-24T21:44:04Z"
    mac: ENC[AES256_GCM,data:u4EFMpGp5xmMchhFDw7mucVFVg4Li83iakhqWLvkx574Eh+4dSmjMni+PPnIr/7rcb+Jh0/qa+rEnxORwtTZ45eCI44m7H8Wm/Qx1J3LZk8AZ6crJw29wM02xfzCO0oPlZsHWBedgbuqGDNhVcm/qdQY9JlFFCO32nKGidGmZTU=,iv:v40ShC4UAQ5TajBvHn9xuMiGJl1yk0dq5zWqMVKoaXs=,tag:WzCHmZuoGBQKx48i6vymTg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
