githubConfigSecret:
    github_token: ENC[AES256_GCM,data:o1EI7VV7dnTj588Eh5WqK47lbMm27FxyvSrnzQWFlWbk6E8i2RKAmg==,iv:TYakP3jEqqbRlUjnJ8oqNHEh3RJPc4i6tqWKHLOCAAM=,tag:uxXmOK7Tn5hVDR+dr2/qyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h0htjej74v08vetp5na0n7phjw6zrqe5lgcpqjyp0td3lugx6f5qk4zhcc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVU3I1RjB2VWlUV0VpamxR
            YUxMUjdvTVF6bmNoWXZVQ2hta3VUVlF5U2lFCldvQ21QL0tucW9PSEpRTk1QQUoy
            akN3a3REWnczQ1MzWnYyc05tQUdYMzQKLS0tIC9nNnVaWVZJV0JhYlkvclZzWG9Q
            K2tuM3NMeFZyR3RVMnRwbEZVN3RER0UKibqd2h9dec1tkHHXu0pgx52Bq0ly+0IN
            967MdoQUZVOwTuYy0fWvPt47UodsKT5VyiB5HZgiRfHTzrDdcwXC7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-30T20:47:06Z"
    mac: ENC[AES256_GCM,data:uKeOn2RSZLnc0+2COqiuFAYdtPw/Xcbu44AuT4/DWZOGZE1MJcXUyv1Ox7kHNkDJwbtGW2EUh1dh3rsLhXrdOnbwZNs9ZQE4JC9qLtdork5XSoA0rCDXEx7JAxqbaqGrMCyoPkuQcaQolyLKGNqFB2ebrEviInr2BAPGXOlzFjk=,iv:ufe8uWRz3KCb/MAZe5s/3ySgMW6JQq+OCvVGQ00f9EY=,tag:sIFHjRigzvSvxU1sxrfIpA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
