---
- name: Setup/Test the misc servers
  hosts: misc_servers
  gather_facts: false
  become: true
  tasks:
    - name: Install the zsh
      ansible.builtin.apt:
        name: zsh
        state: present
        update_cache: true

    - name: Check the zsh is installed
      ansible.builtin.command:
        cmd: zsh --version
      changed_when: false

    - name: Test task
      ansible.builtin.command:
        cmd: zsh --version
      changed_when: false
