---
environments:
  poc: {}
---
releases:
  - name: arc-systems
    namespace: arc-systems
    chart: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
    version: 0.12.1
    values:
      - values/base.yaml
      - values/{{ .Environment.Name }}.yaml
    secrets:
      - secrets/base.yaml
      - secrets/{{ .Environment.Name }}.yaml
