name: CD

on:
  push:
    paths:
      - .github/workflows/cd.yml
      - 'ansible/**'
  workflow_dispatch:

jobs:
  cd:
    runs-on: arc-runner-set
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        working-directory: ansible
        run: pip install -r requirements.txt

      - name: Run playbook
        working-directory: ansible
        run: ansible-playbook -i inventories/poc/hosts.ini playbooks/misc_servers.yml
